name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  nixos-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "system-features = nixos-test benchmark big-parallel kvm"

      - run: nix build .#checks.x86_64-linux.basic
